# Database Configuration
weaviate:
  host: localhost
  port: 8080
  batch_size: 100

qdrant:
  host: localhost
  port: 6333
  batch_size: 100

pgvector:
  host: localhost
  port: 5432
  database: vector_db
  user: postgres
